### ISSUE TITLE
Polymorphic Association for user

### ISSUE THREAD

**Issue by weblee** [leejarvis/hound#3]
Not every app would have the same model for its roles for example in a recent app the client requested different tables for each role ie User, Admin & Partner.

But Admins can login as partners are update items within their portal.  I would be great to be able to track each role and their adjustments made.

Just an idea !

**Comment by leejarvis** [comment]
@weblee Could you try HEAD against your app to ensure this fits your needs before I release again? You'll have to add the `user_type` string column to `hound_actions` for it to work, then use `hound_user` in your `Admin` and `Partner` class. Also make sure `hound_user` returns the correct instance.

**Comment by weblee** [comment]
Nice, From quick testing looks great.  but this app is in dev so I could not say 100% without adding tests. But cracking TY!!!

**Comment by leejarvis** [comment]
Great. I'll push a new version and we'll continue with this as a base.
